title: "Ponete la camiseta"
description: "Ponete la camiseta dentro y fuera de la cancha"
baseurl: ""
url: "https://lacamiseta.org"

collections:
  causes:
    output: true
    permalink: /:slug/
  sections:
    output: false
  actions:
    output: true
    permalink: /acciones/:slug/

defaults:
  - scope:
      type: causes
    values:
      layout: cause

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - design.png
